# Generated by Django 4.0.2 on 2022-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=200, verbose_name='Digite o nome do grupo')),
                ('projeto', models.CharField(max_length=200, verbose_name='Digite o nome do projeto')),
                ('cliente', models.CharField(max_length=200, verbose_name='Digite o nome do cliente')),
                ('n_de_part', models.DecimalField(decimal_places=10, max_digits=100)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do projeto')),
                ('tutorial', models.CharField(max_length=200, verbose_name='tutorial')),
                ('ver', models.CharField(max_length=200, verbose_name='ver')),
                ('status', models.CharField(max_length=200, verbose_name='ver')),
                ('datas', models.DateField()),
            ],
        ),
    ]
