# Generated by Django 4.0.2 on 2022-02-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('email', models.CharField(max_length=10, verbose_name='Email do Usuário')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha')),
                ('adm', models.CharField(blank=True, max_length=1, null=True, verbose_name='Adm')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('universidade', models.CharField(max_length=50, null=True, verbose_name='Universidade')),
                ('lattes', models.CharField(max_length=60, verbose_name='Lattes')),
                ('git', models.CharField(max_length=60, verbose_name='Github')),
                ('observacao', models.CharField(max_length=200, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cadastro em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
