# Generated by Django 4.0.2 on 2022-02-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=None, max_length=15, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default=None, max_length=40, verbose_name='Email do Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default=None, max_length=40, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
