# Generated by Django 4.0.2 on 2022-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_aluno_cpf_aluno_email_aluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
    ]
