# Generated by Django 4.0.2 on 2022-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=200, verbose_name='Nome do Grupo')),
                ('projeto', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('n_de_part', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Número de Participantes')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Projeto')),
                ('ver', models.CharField(max_length=200, verbose_name='ver')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('dataIni', models.DateField(blank=True, verbose_name='Data Inicio')),
                ('dataFim', models.DateField(blank=True, verbose_name='Data Fim')),
                ('tutorial', models.CharField(max_length=200, verbose_name='tutorial')),
            ],
        ),
    ]
