# Generated by Django 4.0.2 on 2022-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='dataFim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='dataIni',
            field=models.DateField(verbose_name='Data Inicio'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='ver',
            field=models.CharField(max_length=200, verbose_name='Link de Visualização'),
        ),
    ]
